### ISSUE TITLE
Tech Req 1 - Add comments to all modules

### ISSUE THREAD

**Issue by asishdahalorg** [blue-sky-app/blue-sky-frontend#40]
This is a series of requirements pulled directly from the Syllabus and so should be given _high priority_ 

Module specs: each executable code module (Java function, JavaScript, etc.) should have a short comment with
1. One or a couple of sentences saying what the module's task is
2. Definitions of input parameters
3. Any error conditions handled by the module
4. Author

**Comment by samwaych** [comment]
This has been completed.
